// frontend-nextjs/src/components/navbar-customer.tsx
"use client";

import React, { useState } from 'react';
import Link from 'next/link';
import { useRouter, usePathname } from 'next/navigation';
import { useCartStore } from '@/store/useCartStore';
import { useAuthStore } from '@/store/useAuthStore';
import { CartDrawer } from './cart-drawer';
import { Button } from '@/components/ui/button';
import { Sheet, SheetContent, SheetHeader, SheetTitle } from '@/components/ui/sheet';
import {
  ShoppingCart,
  Menu as MenuIcon,
  LogOut,
  User,
  ShoppingBag,
  Clock,
  Settings,
  ArrowLeft,
} from 'lucide-react';
import { toast } from 'sonner';

export function NavbarCustomer() {
  const router = useRouter();
  const pathname = usePathname();
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const [cartOpen, setCartOpen] = useState(false);

  const cartItemsCount = useCartStore((state) => state.getCartItemsCount());
  const { authenticated, user, logout } = useAuthStore();

  const handleLogout = () => {
    setSidebarOpen(false);
    logout();
    toast.success('Sesión cerrada correctamente');
    router.push('/');
  };

  const menuItems = [
    { name: 'Menú Cliente', path: '/menu/customer', icon: ShoppingBag },
    { name: 'Mis Pedidos', path: '/customer/deliverys', icon: Clock },
    { name: 'Mi Perfil', path: '/my-profile', icon: Settings },
  ];

  return (
    <>
      <header className="sticky top-0 z-40 w-full bg-ceiba-paper border-b border-ceiba-line shadow-xs">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-18 flex items-center justify-between">
          
          {/* Logo & Back button if not dashboard */}
          <div className="flex items-center gap-4">
            <Button
              size="icon"
              variant="ghost"
              className="lg:hidden rounded-full hover:bg-ceiba-cream border border-ceiba-line text-ceiba-ink cursor-pointer"
              onClick={() => setSidebarOpen(true)}
            >
              <MenuIcon className="w-5 h-5" />
            </Button>

            <Link href="/customer/dashboard" className="flex items-center gap-3">
              <div className="w-10 h-10 rounded-full overflow-hidden border border-ceiba-line shadow-xs">
                {/* eslint-disable-next-line @next/next/no-img-element */}
                <img
                  src="/assets/images/logoarbol.jpg"
                  alt="Ceiba Bar Logo"
                  className="w-full h-full object-cover"
                  onError={(e) => {
                    (e.target as any).src = 'https://images.unsplash.com/photo-1574096079513-d8259312b785?w=80&h=80&fit=crop';
                  }}
                />
              </div>
              <span className="font-bold text-base tracking-wider text-ceiba-ink hidden sm:block">
                Ceiba Bar Cliente
              </span>
            </Link>
          </div>

          {/* Desktop horizontal navigation */}
          <nav className="hidden lg:flex items-center gap-8 font-semibold text-sm tracking-wider text-ceiba-ink">
            {menuItems.map((item) => {
              const Icon = item.icon;
              return (
                <Link
                  key={item.path}
                  href={item.path}
                  className={`flex items-center gap-2 transition-colors hover:text-ceiba-leaf ${
                    pathname === item.path ? 'text-ceiba-leaf' : ''
                  }`}
                >
                  <Icon className="w-4 h-4" />
                  {item.name}
                </Link>
              );
            })}
          </nav>

          {/* Right actions (Cart and Logout / User Details) */}
          <div className="flex items-center gap-4">
            {/* Desktop User Info & Logout */}
            <div className="hidden lg:flex items-center gap-3">
              <div className="text-right">
                <p className="text-xs font-bold text-ceiba-ink">{user?.name || 'Cliente'}</p>
                <p className="text-[10px] text-ceiba-ink/60">{user?.email}</p>
              </div>
              <Button
                size="icon"
                variant="ghost"
                className="rounded-full hover:bg-ceiba-coral/10 hover:text-ceiba-coral text-ceiba-ink border border-transparent hover:border-ceiba-coral/20 cursor-pointer"
                onClick={handleLogout}
                title="Cerrar Sesión"
              >
                <LogOut className="w-4 h-4" />
              </Button>
            </div>

            {/* Cart Button */}
            <Button
              size="icon"
              variant="ghost"
              className="relative rounded-full hover:bg-ceiba-cream border border-ceiba-line text-ceiba-ink cursor-pointer"
              onClick={() => setCartOpen(true)}
            >
              <ShoppingCart className="w-4 h-4" />
              {cartItemsCount > 0 && (
                <span className="absolute -top-1 -right-1 flex h-4 w-4 items-center justify-center rounded-full bg-ceiba-coral text-[8px] font-bold text-white">
                  {cartItemsCount}
                </span>
              )}
            </Button>
          </div>
        </div>
      </header>

      {/* Left Sidebar (Sheet) for Customer Panel */}
      <Sheet open={sidebarOpen} onOpenChange={setSidebarOpen}>
        <SheetContent
          side="left"
          className="w-72 bg-ceiba-cream text-ceiba-ink border-r border-ceiba-line flex flex-col p-6"
          showCloseButton={true}
        >
          <SheetHeader className="pb-4 border-b border-ceiba-line">
            <div className="flex flex-col items-center gap-3 mt-4 text-center">
              <div className="w-16 h-16 rounded-full overflow-hidden border-2 border-ceiba-leaf shadow-sm">
                {/* eslint-disable-next-line @next/next/no-img-element */}
                <img
                  src="/assets/images/logoarbol.jpg"
                  alt="Ceiba Bar Logo"
                  className="w-full h-full object-cover"
                  onError={(e) => {
                    (e.target as any).src = 'https://images.unsplash.com/photo-1574096079513-d8259312b785?w=80&h=80&fit=crop';
                  }}
                />
              </div>
              <div>
                <SheetTitle className="text-lg font-bold text-ceiba-ink">
                  {user?.name || 'Cliente'}
                </SheetTitle>
                <p className="text-xs text-ceiba-ink/60 mt-0.5 truncate max-w-[200px]">
                  {user?.email}
                </p>
              </div>
            </div>
          </SheetHeader>

          {/* Navigation Links */}
          <div className="flex-1 py-6 space-y-2">
            {authenticated && menuItems.map((item) => {
              const Icon = item.icon;
              const isActive = pathname === item.path;
              return (
                <Link
                  key={item.path}
                  href={item.path}
                  onClick={() => setSidebarOpen(false)}
                  className={`flex items-center gap-3.5 px-4 py-3 rounded-xl text-sm font-semibold tracking-wide transition-all ${
                    isActive
                      ? 'bg-ceiba-ink text-ceiba-paper'
                      : 'hover:bg-ceiba-line/50 text-ceiba-ink'
                  }`}
                >
                  <Icon className={`w-5 h-5 ${isActive ? 'text-ceiba-leaf' : 'text-ceiba-ink/75'}`} />
                  {item.name}
                </Link>
              );
            })}

            {!authenticated && (
              <Link
                href="/login"
                onClick={() => setSidebarOpen(false)}
                className="flex items-center gap-3.5 px-4 py-3 rounded-xl text-sm font-semibold tracking-wide hover:bg-ceiba-line/50 text-ceiba-ink"
              >
                <User className="w-5 h-5 text-ceiba-ink/75" />
                Iniciar Sesión
              </Link>
            )}
          </div>

          {/* Footer with logout */}
          {authenticated && (
            <div className="pt-4 border-t border-ceiba-line mt-auto">
              <Button
                variant="outline"
                className="w-full justify-start gap-3 border-ceiba-coral text-ceiba-coral hover:bg-ceiba-coral hover:text-white rounded-xl py-5 font-bold transition-all"
                onClick={handleLogout}
              >
                <LogOut className="w-4 h-4" />
                Cerrar Sesión
              </Button>
            </div>
          )}
        </SheetContent>
      </Sheet>

      <CartDrawer open={cartOpen} onOpenChange={setCartOpen} />
    </>
  );
}

// deliveryFront/delivery-frontendd/src/app/navbar-customer/navbar-customer.component.ts
import { CommonModule } from '@angular/common';
import { ChangeDetectorRef, Component, computed } from '@angular/core';
import { Router, RouterModule } from '@angular/router';
import { AvatarModule } from 'primeng/avatar';
import { BadgeModule } from 'primeng/badge';
import { ButtonModule } from 'primeng/button';
import { DrawerModule } from 'primeng/drawer';
import { MenuModule } from 'primeng/menu';
import { OverlayBadgeModule } from 'primeng/overlaybadge';
import { ProgressSpinnerModule } from 'primeng/progressspinner';
import { UsersService } from '../services/users.service';
import { CartService } from '../services/cart.service';
import { environment } from '../../environments/environment';

@Component({
  selector: 'app-navbar-customer',
  imports: [AvatarModule, BadgeModule,OverlayBadgeModule,ButtonModule,
    DrawerModule,CommonModule,RouterModule,DrawerModule,MenuModule, ProgressSpinnerModule],
  templateUrl: './navbar-customer.component.html',
  styleUrl: './navbar-customer.component.scss'
})
export class NavbarCustomerComponent {

  visible: boolean = false;

  full = computed(() => !!this.usersService.userData());

  constructor(public usersService: UsersService, private router: Router,public cartService: CartService,private cdr: ChangeDetectorRef) {}

cerrarSesion() {
    this.usersService.logout();
  this.router.navigate(['/inicio']);
  }


  // Crea un signal computado que siempre emite una nueva referencia
  cartItems = computed(() => this.cartService.getCartItems());

  

  
  



// Controlar la visibilidad del drawer
  cartDrawerVisible: boolean = false;
 
   // Métodos del carrito (ahora usan directamente el servicio)
  removeFromCart(productId: number): void {
    this.cartService.removeFromCart(productId);
    this.cdr.markForCheck();
  }

  increaseQuantity(productId: number): void {
    const item = this.cartService.getCartItems().find(cartItem => cartItem.product.id === productId);
    if (item) {
      this.cartService.updateQuantity(productId, item.quantity + 1);
      this.cdr.markForCheck();
    }
  }

  decreaseQuantity(productId: number): void {
    const item = this.cartService.getCartItems().find(cartItem => cartItem.product.id === productId);
    if (item && item.quantity > 1) {
      this.cartService.updateQuantity(productId, item.quantity - 1);
      this.cdr.markForCheck();
    } else {
      this.removeFromCart(productId);
    }
  }

  clearCart(): void {
    this.cartService.clearCart();
    this.cdr.markForCheck();
  }

  checkout(): void {
    console.log('Proceder al checkout:', this.cartService.getCartItems());
    this.cartDrawerVisible = false;
  }

  getImageUrl(imagePath: string | null): string {
    if (!imagePath) {
      return 'https://primefaces.org/cdn/primeng/images/galleria/galleria10.jpg';
    }
    
    if (imagePath.startsWith('http')) {
      return imagePath;
    }
    const normalizedPath = imagePath.startsWith('/') ? imagePath : `/${imagePath}`;
    return `${environment.imageBasePathProducts}${normalizedPath}`;
  }
}

@if(!full()){
<header class="sticky top-0 z-40 w-full bg-ceiba-paper border-b border-ceiba-line shadow-xs">
  <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-18 flex items-center justify-between">
    
    <div class="flex items-center gap-4">
      <button (click)="visible = true"
        class="lg:hidden p-2 rounded-full hover:bg-ceiba-cream border border-ceiba-line text-ceiba-ink cursor-pointer flex items-center justify-center">
        <i class="pi pi-bars text-lg"></i>
      </button>

      <a routerLink="/" class="flex items-center gap-3 no-underline">
        <div class="w-10 h-10 rounded-full overflow-hidden border border-ceiba-line shadow-xs">
          <img src="assets/images/logoarbol.jpg" alt="Ceiba Bar Logo" class="w-full h-full object-cover" />
        </div>
        <span class="font-bold text-base tracking-wider text-ceiba-ink hidden sm:block">
          Ceiba Bar
        </span>
      </a>
    </div>

    <!-- Desktop nav links -->
    <nav class="hidden lg:flex items-center gap-8 font-semibold text-sm tracking-wider text-ceiba-ink">
      <a routerLink="/login" class="flex items-center gap-2 transition-colors hover:text-ceiba-leaf no-underline">
        <i class="pi pi-sign-in"></i>
        Iniciar Sesión
      </a>
    </nav>

    <!-- Right Actions -->
    <div class="flex items-center gap-4">
      <button (click)="cartDrawerVisible = true"
        class="relative p-2.5 rounded-full hover:bg-ceiba-cream border border-ceiba-line text-ceiba-ink cursor-pointer flex items-center justify-center">
        <i class="pi pi-shopping-cart text-lg"></i>
        <span *ngIf="cartService.cartItemsCount() > 0"
          class="absolute -top-1 -right-1 flex h-4.5 w-4.5 items-center justify-center rounded-full bg-ceiba-coral text-[9px] font-extrabold text-white">
          {{ cartService.cartItemsCount() }}
        </span>
      </button>
    </div>

  </div>
</header>
}@else {
<header class="sticky top-0 z-40 w-full bg-ceiba-paper border-b border-ceiba-line shadow-xs">
  <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-18 flex items-center justify-between">
    
    <div class="flex items-center gap-4">
      <button (click)="visible = true"
        class="lg:hidden p-2 rounded-full hover:bg-ceiba-cream border border-ceiba-line text-ceiba-ink cursor-pointer flex items-center justify-center">
        <i class="pi pi-bars text-lg"></i>
      </button>

      <a routerLink="/customer/dashboard" class="flex items-center gap-3 no-underline">
        <div class="w-10 h-10 rounded-full overflow-hidden border border-ceiba-line shadow-xs">
          <img src="assets/images/logoarbol.jpg" alt="Ceiba Bar Logo" class="w-full h-full object-cover" />
        </div>
        <span class="font-bold text-base tracking-wider text-ceiba-ink hidden sm:block">
          Ceiba Bar
        </span>
      </a>
    </div>

    <!-- Desktop nav links -->
    <nav class="hidden lg:flex items-center gap-8 font-semibold text-sm tracking-wider text-ceiba-ink">
      <a routerLink="/menu/customer" class="flex items-center gap-2 transition-colors hover:text-ceiba-leaf no-underline">
        <i class="pi pi-shopping-bag text-sm"></i>
        Menú
      </a>
      <a routerLink="/customer/deliverys" class="flex items-center gap-2 transition-colors hover:text-ceiba-leaf no-underline">
        <i class="pi pi-truck text-sm"></i>
        Pedidos
      </a>
      <a routerLink="/my-profile" class="flex items-center gap-2 transition-colors hover:text-ceiba-leaf no-underline">
        <i class="pi pi-user text-sm"></i>
        Perfil
      </a>
    </nav>

    <!-- Right Actions -->
    <div class="flex items-center gap-4">
      <div class="hidden lg:flex items-center gap-3 text-right">
        <p class="text-xs font-bold text-ceiba-ink m-0">{{ usersService.userData()?.user?.name || 'Cliente' }}</p>
        <button (click)="cerrarSesion()"
          class="p-2 rounded-full hover:bg-ceiba-coral/10 hover:text-ceiba-coral text-ceiba-ink border border-transparent hover:border-ceiba-coral/20 cursor-pointer flex items-center justify-center"
          title="Cerrar Sesión">
          <i class="pi pi-sign-out text-sm"></i>
        </button>
      </div>

      <button (click)="cartDrawerVisible = true"
        class="relative p-2.5 rounded-full hover:bg-ceiba-cream border border-ceiba-line text-ceiba-ink cursor-pointer flex items-center justify-center">
        <i class="pi pi-shopping-cart text-lg"></i>
        <span *ngIf="cartService.cartItemsCount() > 0"
          class="absolute -top-1 -right-1 flex h-4.5 w-4.5 items-center justify-center rounded-full bg-ceiba-coral text-[9px] font-extrabold text-white">
          {{ cartService.cartItemsCount() }}
        </span>
      </button>
    </div>

  </div>
</header>
}

<!-- Left Drawer for Mobile Navigation -->
<p-drawer [(visible)]="visible" position="left" [blockScroll]="true" [dismissible]="true"
  [showCloseIcon]="true" [style]="{'width': '300px'}" styleClass="ceiba-sidebar-left">
  <ng-template pTemplate="header">
    <div class="flex items-center gap-3 py-2">
      <div class="w-12 h-12 rounded-full overflow-hidden border border-ceiba-line shadow-xs">
        <img src="assets/images/logoarbol.jpg" alt="Ceiba Bar Logo" class="w-full h-full object-cover" />
      </div>
      <div class="text-left">
        <h4 class="font-bold text-sm text-ceiba-ink m-0">{{ usersService.userData()?.user?.name || 'Cliente' }}</h4>
        <p class="text-[10px] text-ceiba-ink/60 m-0">{{ usersService.userData()?.user?.email || 'Bienvenido' }}</p>
      </div>
    </div>
  </ng-template>

  <div class="flex flex-col h-full py-4 justify-between">
    <div class="space-y-2">
      @if(!full()) {
        <a routerLink="/login" (click)="visible = false"
          class="flex items-center gap-3 px-4 py-3 rounded-xl text-sm font-semibold tracking-wide hover:bg-ceiba-line/10 text-ceiba-ink no-underline transition-all">
          <i class="pi pi-sign-in text-ceiba-ink/75"></i>
          Iniciar Sesión
        </a>
      } @else {
        <a routerLink="/menu/customer" (click)="visible = false"
          class="flex items-center gap-3 px-4 py-3 rounded-xl text-sm font-semibold tracking-wide hover:bg-ceiba-line/10 text-ceiba-ink no-underline transition-all">
          <i class="pi pi-shopping-bag text-ceiba-ink/75"></i>
          Menú
        </a>
        <a routerLink="/customer/deliverys" (click)="visible = false"
          class="flex items-center gap-3 px-4 py-3 rounded-xl text-sm font-semibold tracking-wide hover:bg-ceiba-line/10 text-ceiba-ink no-underline transition-all">
          <i class="pi pi-truck text-ceiba-ink/75"></i>
          Pedidos
        </a>
        <a routerLink="/my-profile" (click)="visible = false"
          class="flex items-center gap-3 px-4 py-3 rounded-xl text-sm font-semibold tracking-wide hover:bg-ceiba-line/10 text-ceiba-ink no-underline transition-all">
          <i class="pi pi-user text-ceiba-ink/75"></i>
          Perfil
        </a>
      }
    </div>

    @if(full()) {
      <div class="pt-4 border-t border-ceiba-line mt-auto">
        <button pButton label="Cerrar Sesión" icon="pi pi-sign-out"
          class="w-full justify-start gap-3 border-ceiba-coral text-ceiba-coral hover:bg-ceiba-coral hover:text-white rounded-xl py-3 font-bold transition-all p-button-outlined"
          (click)="cerrarSesion(); visible = false">
        </button>
      </div>
    }
  </div>
</p-drawer>

<!-- Right Drawer for Cart -->
<p-drawer [(visible)]="cartDrawerVisible" position="right" [blockScroll]="true" [dismissible]="true"
  [showCloseIcon]="true" [style]="{'width': '450px'}" styleClass="ceiba-cart-drawer">
  
  <ng-template pTemplate="header">
    <div class="flex items-center justify-between w-full pr-4 py-1">
      <h3 class="font-extrabold text-lg text-ceiba-ink m-0">Tu Carrito 🛒</h3>
      <span class="bg-ceiba-cream px-3 py-1.5 rounded-full border border-ceiba-line text-xs font-bold text-ceiba-ink">
        {{ cartService.cartItemsCount() }} items
      </span>
    </div>
  </ng-template>

  <div class="flex flex-col h-full justify-between">
    <!-- Items list -->
    <div class="flex-1 overflow-y-auto py-4 space-y-4">
      @if(cartService.getCartItems().length === 0){
        <div class="flex flex-col items-center justify-center py-16 text-center">
          <i class="pi pi-shopping-cart text-5xl text-ceiba-ink/20 mb-3"></i>
          <p class="font-bold text-sm text-ceiba-ink">Tu carrito está vacío</p>
          <button pButton label="Seguir Comprando" class="mt-4 bg-ceiba-ink text-white border-none rounded-xl py-2 px-4 text-xs font-bold"
            (click)="cartDrawerVisible = false"></button>
        </div>
      } @else {
        <div *ngFor="let item of cartService.getCartItems()"
          class="flex items-center gap-4 bg-white border border-ceiba-line p-3 rounded-2xl shadow-xs hover:shadow-md transition-all">
          <div class="w-16 h-16 rounded-xl overflow-hidden border border-ceiba-line flex-shrink-0">
            <img [src]="getImageUrl(item.product.image)" [alt]="item.product.name" class="w-full h-full object-cover" />
          </div>
          
          <div class="flex-1 text-left min-w-0">
            <h4 class="font-extrabold text-sm text-ceiba-ink truncate m-0">{{ item.product.name }}</h4>
            <p class="text-xs text-ceiba-leaf-dark font-extrabold mt-1 m-0">{{ item.product.price | currency:'MXN':'symbol':'1.2-2' }}</p>
          </div>
          
          <div class="flex flex-col items-end gap-2">
            <div class="flex items-center bg-ceiba-cream border border-ceiba-line rounded-full p-1 gap-2 scale-90">
              <button (click)="decreaseQuantity(item.product.id)"
                class="w-6 h-6 rounded-full bg-white border border-ceiba-line text-ceiba-ink font-bold hover:bg-ceiba-cream transition-all flex items-center justify-center">-</button>
              <span class="font-extrabold text-xs text-ceiba-ink min-w-[15px] text-center">{{ item.quantity }}</span>
              <button (click)="increaseQuantity(item.product.id)"
                class="w-6 h-6 rounded-full bg-white border border-ceiba-line text-ceiba-ink font-bold hover:bg-ceiba-cream transition-all flex items-center justify-center">+</button>
            </div>
            
            <button (click)="removeFromCart(item.product.id)"
              class="p-2 rounded-full bg-ceiba-coral/10 hover:bg-ceiba-coral/20 text-ceiba-coral border-none cursor-pointer flex items-center justify-center scale-90">
              <i class="pi pi-trash text-xs"></i>
            </button>
          </div>
        </div>
      }
    </div>

    <!-- Footer total and actions -->
    <div *ngIf="cartService.getCartItems().length > 0" class="pt-6 border-t border-ceiba-line space-y-4">
      <div class="flex items-center justify-between px-2">
        <span class="text-sm font-semibold text-ceiba-ink/70">Subtotal</span>
        <span class="font-black text-xl text-ceiba-ink">{{ cartService.cartTotal() | currency:'MXN':'symbol':'1.2-2' }}</span>
      </div>
      
      <div class="grid grid-cols-2 gap-3 pb-6">
        <button pButton label="Limpiar" icon="pi pi-trash"
          class="border-ceiba-line text-ceiba-ink hover:bg-ceiba-cream rounded-xl py-3 font-bold transition-all p-button-outlined"
          (click)="clearCart()"></button>
        <button pButton label="Pagar" icon="pi pi-credit-card"
          class="bg-ceiba-leaf hover:bg-ceiba-leaf-dark text-white border-none rounded-xl py-3 font-bold transition-all"
          (click)="cartService.finalizarCompra(); cartDrawerVisible = false"></button>
      </div>
    </div>
  </div>

</p-drawer>
