// frontend-nextjs/src/components/navbar-admin.tsx
"use client";

import React, { useState } from 'react';
import Link from 'next/link';
import { useRouter, usePathname } from 'next/navigation';
import { useAuthStore } from '@/store/useAuthStore';
import { Button } from '@/components/ui/button';
import { Sheet, SheetContent, SheetHeader, SheetTitle } from '@/components/ui/sheet';
import {
  Menu as MenuIcon,
  LogOut,
  User,
  ShoppingBag,
  Users,
  Settings,
  ClipboardList,
} from 'lucide-react';
import { toast } from 'sonner';

export function NavbarAdmin() {
  const router = useRouter();
  const pathname = usePathname();
  const [sidebarOpen, setSidebarOpen] = useState(false);

  const { authenticated, user, logout } = useAuthStore();

  const handleLogout = () => {
    setSidebarOpen(false);
    logout();
    toast.success('Sesión cerrada correctamente');
    router.push('/');
  };

  const menuItems = [
    { name: 'Usuarios', path: '/admin/users', icon: Users },
    { name: 'Productos', path: '/admin/products', icon: ShoppingBag },
    { name: 'Pedidos/Entregas', path: '/admin/orders', icon: ClipboardList },
    { name: 'Mi Perfil', path: '/my-profile', icon: Settings },
  ];

  return (
    <>
      <header className="sticky top-0 z-40 w-full bg-ceiba-paper border-b border-ceiba-line shadow-xs">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-18 flex items-center justify-between">
          <div className="flex items-center gap-4">
            <Button
              size="icon"
              variant="ghost"
              className="lg:hidden rounded-full hover:bg-ceiba-cream border border-ceiba-line text-ceiba-ink cursor-pointer"
              onClick={() => setSidebarOpen(true)}
            >
              <MenuIcon className="w-5 h-5" />
            </Button>

            <Link href="/admin/dashboard" className="flex items-center gap-3">
              <div className="w-10 h-10 rounded-full overflow-hidden border border-ceiba-line shadow-xs">
                {/* eslint-disable-next-line @next/next/no-img-element */}
                <img
                  src="/assets/images/logoarbol.jpg"
                  alt="Ceiba Bar Logo"
                  className="w-full h-full object-cover"
                  onError={(e) => {
                    (e.target as any).src = 'https://images.unsplash.com/photo-1574096079513-d8259312b785?w=80&h=80&fit=crop';
                  }}
                />
              </div>
              <span className="font-bold text-base tracking-wider text-ceiba-ink hidden sm:block">
                Ceiba Bar Admin
              </span>
            </Link>
          </div>

          {/* Desktop horizontal navigation */}
          <nav className="hidden lg:flex items-center gap-8 font-semibold text-sm tracking-wider text-ceiba-ink">
            {menuItems.map((item) => {
              const Icon = item.icon;
              return (
                <Link
                  key={item.path}
                  href={item.path}
                  className={`flex items-center gap-2 transition-colors hover:text-ceiba-leaf ${
                    pathname === item.path ? 'text-ceiba-leaf' : ''
                  }`}
                >
                  <Icon className="w-4 h-4" />
                  {item.name}
                </Link>
              );
            })}
          </nav>

          {/* Right actions */}
          <div className="flex items-center gap-4">
            <div className="hidden lg:flex items-center gap-3">
              <div className="text-right">
                <p className="text-xs font-bold text-ceiba-ink">{user?.name || 'Admin'}</p>
                <p className="text-[10px] text-ceiba-leaf font-bold">Administrador</p>
              </div>
              <Button
                size="icon"
                variant="ghost"
                className="rounded-full hover:bg-ceiba-coral/10 hover:text-ceiba-coral text-ceiba-ink cursor-pointer"
                onClick={handleLogout}
                title="Cerrar Sesión"
              >
                <LogOut className="w-4 h-4" />
              </Button>
            </div>
          </div>
        </div>
      </header>

      {/* Left Sidebar (Sheet) for Admin Panel */}
      <Sheet open={sidebarOpen} onOpenChange={setSidebarOpen}>
        <SheetContent
          side="left"
          className="w-72 bg-ceiba-cream text-ceiba-ink border-r border-ceiba-line flex flex-col p-6"
          showCloseButton={true}
        >
          <SheetHeader className="pb-4 border-b border-ceiba-line">
            <div className="flex flex-col items-center gap-3 mt-4 text-center">
              <div className="w-16 h-16 rounded-full overflow-hidden border-2 border-ceiba-leaf shadow-sm bg-white">
                {/* eslint-disable-next-line @next/next/no-img-element */}
                <img
                  src="/assets/images/logoarbol.jpg"
                  alt="Ceiba Bar Logo"
                  className="w-full h-full object-cover"
                  onError={(e) => {
                    (e.target as any).src = 'https://images.unsplash.com/photo-1574096079513-d8259312b785?w=80&h=80&fit=crop';
                  }}
                />
              </div>
              <div>
                <SheetTitle className="text-lg font-bold text-ceiba-ink">
                  {user?.name || 'Administrador'}
                </SheetTitle>
                <p className="text-xs text-ceiba-leaf font-bold mt-0.5">
                  Panel de Administración
                </p>
              </div>
            </div>
          </SheetHeader>

          {/* Navigation Links */}
          <div className="flex-1 py-6 space-y-2">
            {authenticated && menuItems.map((item) => {
              const Icon = item.icon;
              const isActive = pathname === item.path;
              return (
                <Link
                  key={item.path}
                  href={item.path}
                  onClick={() => setSidebarOpen(false)}
                  className={`flex items-center gap-3.5 px-4 py-3 rounded-xl text-sm font-semibold tracking-wide transition-all ${
                    isActive
                      ? 'bg-ceiba-ink text-ceiba-paper'
                      : 'hover:bg-ceiba-line/50 text-ceiba-ink'
                  }`}
                >
                  <Icon className={`w-5 h-5 ${isActive ? 'text-ceiba-leaf' : 'text-ceiba-ink/75'}`} />
                  {item.name}
                </Link>
              );
            })}

            {!authenticated && (
              <Link
                href="/login"
                onClick={() => setSidebarOpen(false)}
                className="flex items-center gap-3.5 px-4 py-3 rounded-xl text-sm font-semibold tracking-wide hover:bg-ceiba-line/50 text-ceiba-ink"
              >
                <User className="w-5 h-5 text-ceiba-ink/75" />
                Iniciar Sesión
              </Link>
            )}
          </div>

          {/* Footer with logout */}
          {authenticated && (
            <div className="pt-4 border-t border-ceiba-line mt-auto">
              <Button
                variant="outline"
                className="w-full justify-start gap-3 border-ceiba-coral text-ceiba-coral hover:bg-ceiba-coral hover:text-white rounded-xl py-5 font-bold transition-all"
                onClick={handleLogout}
              >
                <LogOut className="w-4 h-4" />
                Cerrar Sesión
              </Button>
            </div>
          )}
        </SheetContent>
      </Sheet>
    </>
  );
}

// deliveryFront/delivery-frontendd/src/app/navbar-admin/navbar-admin.component.ts
import { Component, effect } from '@angular/core';
import {  AvatarModule } from 'primeng/avatar';
import { BadgeModule } from 'primeng/badge';
import { ButtonModule } from 'primeng/button';
import { OverlayBadgeModule } from 'primeng/overlaybadge';
import { DrawerModule } from 'primeng/drawer';
import { CommonModule } from '@angular/common';
import { Router, RouterModule } from '@angular/router';
import { MenuItem } from 'primeng/api';
import { MenuModule } from 'primeng/menu';
import { Subscription } from 'rxjs';
import { UsersService } from '../services/users.service';
import { ProgressSpinnerModule } from 'primeng/progressspinner';
import { LoadingService } from '../services/loading.service';
import { environment } from '../../environments/environment';
import { UserInfo } from '../model/Dtos';


@Component({
  selector: 'app-navbar-admin',
  imports: [AvatarModule, BadgeModule,OverlayBadgeModule,ButtonModule,
    DrawerModule,CommonModule,RouterModule,DrawerModule,MenuModule, ProgressSpinnerModule],
  templateUrl: './navbar-admin.component.html',
  styleUrl: './navbar-admin.component.scss'
})
export class NavbarAdminComponent {
  visible: boolean = false;
 

  user: UserInfo | null = null;                   
  userImage: string = '';           
  userName: string = 'Usuario';      
 

  constructor(
    private usersService: UsersService,
    private router: Router,
    
  ) {
    effect(() => {
      const data = this.usersService.userData();
      if (data && data.user) {
        this.user = data.user;
      }
    });
  }
  

  ngOnInit(): void {
   

    // Opcional: forzar carga si aún no hay datos (por si entras directo a una ruta)
    if (!this.usersService.userData()) {
      this.usersService.getUserInfo().subscribe();
    }
  }

  // Helper para construir la URL de la imagen
  getUserImageUrl(imagePath: string | null | undefined): string {
    const defaultImage = 'https://primefaces.org/cdn/primeng/images/galleria/galleria10.jpg';
    
    if (!imagePath) return defaultImage;
    if (imagePath.startsWith('http')) return imagePath;

    const base = environment.imageBasePathUsers;
    const normalized = imagePath.startsWith('/') ? imagePath : `/${imagePath}`;
    return `${base}${normalized}`;
  }

  goToProfile() {
    console.log(this.user)
    this.router.navigate(['/my-profile']);
  }

  ngOnDestroy(): void {
    // this.userSub?.unsubscribe(); // Ya no es necesario con signals
  }

 // Métodos para los eventos click
  goToUsuarios() {
   this.router.navigate(['admin/users']);
  }

  goToProductos() {
    console.log('Navegando a Productos');
    this.router.navigate(['/admin/products']);
  }

  goToEntregas() {
    console.log('Navegando a Entregas');
    this.visible = false;
    // this.router.navigate(['/entregas']);
  }



  cerrarSesion() {
    this.usersService.logout();
  this.router.navigate(['/inicio']);
  }

}

<header class="sticky top-0 z-40 w-full bg-ceiba-paper border-b border-ceiba-line shadow-xs">
  <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-18 flex items-center justify-between">
    
    <div class="flex items-center gap-4">
      <button (click)="visible = true"
        class="lg:hidden p-2 rounded-full hover:bg-ceiba-cream border border-ceiba-line text-ceiba-ink cursor-pointer flex items-center justify-center">
        <i class="pi pi-bars text-lg"></i>
      </button>

      <a routerLink="/admin/dashboard" class="flex items-center gap-3 no-underline">
        <div class="w-10 h-10 rounded-full overflow-hidden border border-ceiba-line shadow-xs">
          <img src="assets/images/logoarbol.jpg" alt="Ceiba Bar Logo" class="w-full h-full object-cover" />
        </div>
        <span class="font-bold text-base tracking-wider text-ceiba-ink hidden sm:block">
          Ceiba Bar Administrador
        </span>
      </a>
    </div>

    <!-- Desktop nav links -->
    <nav class="hidden lg:flex items-center gap-8 font-semibold text-sm tracking-wider text-ceiba-ink">
      <a (click)="goToUsuarios()" class="flex items-center gap-2 transition-colors hover:text-ceiba-leaf no-underline cursor-pointer">
        <i class="pi pi-user text-sm"></i>
        Usuarios
      </a>
      <a (click)="goToProductos()" class="flex items-center gap-2 transition-colors hover:text-ceiba-leaf no-underline cursor-pointer">
        <i class="pi pi-shopping-bag text-sm"></i>
        Productos
      </a>
      <a (click)="goToEntregas()" class="flex items-center gap-2 transition-colors hover:text-ceiba-leaf no-underline cursor-pointer">
        <i class="pi pi-truck text-sm"></i>
        Entregas
      </a>
      <a (click)="goToProfile()" class="flex items-center gap-2 transition-colors hover:text-ceiba-leaf no-underline cursor-pointer">
        <i class="pi pi-cog text-sm"></i>
        Perfil
      </a>
    </nav>

    <!-- Right Actions -->
    <div class="flex items-center gap-4">
      <div class="hidden lg:flex items-center gap-3 text-right">
        <p class="text-xs font-bold text-ceiba-ink m-0">{{ user?.name || 'Administrador' }}</p>
        <button (click)="cerrarSesion()"
          class="p-2 rounded-full hover:bg-ceiba-coral/10 hover:text-ceiba-coral text-ceiba-ink border border-transparent hover:border-ceiba-coral/20 cursor-pointer flex items-center justify-center"
          title="Cerrar Sesión">
          <i class="pi pi-sign-out text-sm"></i>
        </button>
      </div>
    </div>

  </div>
</header>

<!-- Left Drawer for Mobile Navigation -->
<p-drawer [(visible)]="visible" position="left" [blockScroll]="true" [dismissible]="true"
  [showCloseIcon]="true" [style]="{'width': '300px'}" styleClass="ceiba-sidebar-left">
  <ng-template pTemplate="header">
    <div class="flex items-center gap-3 py-2">
      <div class="w-12 h-12 rounded-full overflow-hidden border border-ceiba-line shadow-xs">
        <img src="assets/images/logoarbol.jpg" alt="Ceiba Bar Logo" class="w-full h-full object-cover" />
      </div>
      <div class="text-left">
        <h4 class="font-bold text-sm text-ceiba-ink m-0">{{ user?.name || 'Administrador' }}</h4>
        <p class="text-[10px] text-ceiba-ink/60 m-0">{{ user?.email || 'Panel Admin' }}</p>
      </div>
    </div>
  </ng-template>

  <div class="flex flex-col h-full py-4 justify-between">
    <div class="space-y-2">
      <a (click)="goToUsuarios(); visible = false"
        class="flex items-center gap-3 px-4 py-3 rounded-xl text-sm font-semibold tracking-wide hover:bg-ceiba-line/10 text-ceiba-ink no-underline transition-all cursor-pointer">
        <i class="pi pi-user text-ceiba-ink/75"></i>
        Usuarios
      </a>
      <a (click)="goToProductos(); visible = false"
        class="flex items-center gap-3 px-4 py-3 rounded-xl text-sm font-semibold tracking-wide hover:bg-ceiba-line/10 text-ceiba-ink no-underline transition-all cursor-pointer">
        <i class="pi pi-shopping-bag text-ceiba-ink/75"></i>
        Productos
      </a>
      <a (click)="goToEntregas(); visible = false"
        class="flex items-center gap-3 px-4 py-3 rounded-xl text-sm font-semibold tracking-wide hover:bg-ceiba-line/10 text-ceiba-ink no-underline transition-all cursor-pointer">
        <i class="pi pi-truck text-ceiba-ink/75"></i>
        Entregas
      </a>
      <a (click)="goToProfile(); visible = false"
        class="flex items-center gap-3 px-4 py-3 rounded-xl text-sm font-semibold tracking-wide hover:bg-ceiba-line/10 text-ceiba-ink no-underline transition-all cursor-pointer">
        <i class="pi pi-cog text-ceiba-ink/75"></i>
        Perfil
      </a>
    </div>

    <div class="pt-4 border-t border-ceiba-line mt-auto">
      <button pButton label="Cerrar Sesión" icon="pi pi-sign-out"
        class="w-full justify-start gap-3 border-ceiba-coral text-ceiba-coral hover:bg-ceiba-coral hover:text-white rounded-xl py-3 font-bold transition-all p-button-outlined"
        (click)="cerrarSesion(); visible = false">
      </button>
    </div>
  </div>
</p-drawer>
