// frontend-nextjs/src/components/navbar-home.tsx
"use client";

import React, { useState, useEffect } from 'react';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { useCartStore } from '@/store/useCartStore';
import { useAuthStore } from '@/store/useAuthStore';
import { CartDrawer } from './cart-drawer';
import { Button } from '@/components/ui/button';
import {
  ShoppingCart,
  User,
  Menu,
  X,
  PhoneCall,
} from 'lucide-react';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';

function Facebook(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      {...props}
    >
      <path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z" />
    </svg>
  );
}

function Instagram(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      {...props}
    >
      <rect width="20" height="20" x="2" y="2" rx="5" ry="5" />
      <path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z" />
      <line x1="17.5" x2="17.51" y1="6.5" y2="6.5" />
    </svg>
  );
}

export function NavbarHome() {
  const pathname = usePathname();
  const [cartOpen, setCartOpen] = useState(false);
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
  const [isScrolled, setIsScrolled] = useState(false);

  const cartItemsCount = useCartStore((state) => state.getCartItemsCount());
  const { authenticated, user, logout } = useAuthStore();

  useEffect(() => {
    const handleScroll = () => {
      if (window.scrollY > 10) {
        setIsScrolled(true);
      } else {
        setIsScrolled(false);
      }
    };
    window.addEventListener('scroll', handleScroll);
    return () => window.removeEventListener('scroll', handleScroll);
  }, []);

  const navLinks = [
    { name: 'INICIO', path: '/' },
  ];

  const menuItems = [
    { name: 'Drinks', path: '/menu/drinks' },
    { name: 'Snacks', path: '/menu/snack' },
    { name: 'Recetario', path: '/menu/recetario' },
  ];

  return (
    <>
      <header
        className={`sticky top-0 z-40 w-full transition-all duration-300 ${
          isScrolled
            ? 'bg-ceiba-paper/90 backdrop-blur-md border-b border-ceiba-line shadow-xs'
            : 'bg-transparent'
        }`}
      >
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-18 flex items-center justify-between">
          {/* Logo */}
          <Link href="/" className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-full overflow-hidden border border-ceiba-line shadow-xs">
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img
                src="/assets/images/logoarbol.jpg"
                alt="Ceiba Bar Logo"
                className="w-full h-full object-cover"
                onError={(e) => {
                  // Fallback si no existe el asset local en Next.js
                  (e.target as any).src = 'https://images.unsplash.com/photo-1574096079513-d8259312b785?w=80&h=80&fit=crop';
                }}
              />
            </div>
            <span className="font-bold text-lg tracking-wider text-ceiba-ink hidden sm:block">
              CEIBA BAR
            </span>
          </Link>

          {/* Links desktop */}
          <nav className="hidden lg:flex items-center gap-8 font-semibold text-sm tracking-widest text-ceiba-ink">
            {navLinks.map((link) => (
              <Link
                key={link.path}
                href={link.path}
                className={`transition-colors hover:text-ceiba-leaf ${
                  pathname === link.path ? 'text-ceiba-leaf' : ''
                }`}
              >
                {link.name}
              </Link>
            ))}

            <DropdownMenu>
              <DropdownMenuTrigger className="flex items-center gap-1 hover:text-ceiba-leaf transition-colors cursor-pointer outline-none select-none">
                MENÚ
                <span className="text-[10px]">▼</span>
              </DropdownMenuTrigger>
              <DropdownMenuContent className="bg-ceiba-paper border border-ceiba-line text-ceiba-ink rounded-lg shadow-md p-1 min-w-40 mt-1">
                {menuItems.map((item) => (
                  <DropdownMenuItem
                    key={item.path}
                    render={
                      <Link
                        href={item.path}
                        className="w-full flex px-3 py-2 text-xs hover:bg-ceiba-cream hover:text-ceiba-leaf rounded-md transition-all cursor-pointer font-medium"
                      />
                    }
                  >
                    {item.name}
                  </DropdownMenuItem>
                ))}
              </DropdownMenuContent>
            </DropdownMenu>
          </nav>

          {/* Botones de acción desktop */}
          <div className="hidden lg:flex items-center gap-5">
            {/* User Profile / Login */}
            {authenticated ? (
              <DropdownMenu>
                <DropdownMenuTrigger className="w-10 h-10 rounded-full bg-ceiba-cream flex items-center justify-center cursor-pointer border border-ceiba-line outline-none hover:bg-ceiba-line transition-all">
                  <User className="w-5 h-5 text-ceiba-ink" />
                </DropdownMenuTrigger>
                <DropdownMenuContent className="bg-ceiba-paper border border-ceiba-line text-ceiba-ink rounded-lg shadow-md p-1 min-w-48 mt-1">
                  <DropdownMenuItem
                    render={
                      <Link
                        href={
                          user?.primaryRole === 'ADMIN'
                            ? '/admin/dashboard'
                            : user?.primaryRole === 'DRIVER'
                            ? '/drivers/dashboard'
                            : '/customer/dashboard'
                        }
                        className="w-full flex px-3 py-2 text-xs hover:bg-ceiba-cream rounded-md transition-all font-semibold"
                      />
                    }
                  >
                    Panel de Control
                  </DropdownMenuItem>
                  <DropdownMenuItem
                    render={
                      <Link
                        href="/my-profile"
                        className="w-full flex px-3 py-2 text-xs hover:bg-ceiba-cream rounded-md transition-all font-semibold"
                      />
                    }
                  >
                    Mi Perfil
                  </DropdownMenuItem>
                  <DropdownMenuItem
                    onClick={() => logout()}
                    className="w-full flex px-3 py-2 text-xs hover:bg-ceiba-coral/10 text-ceiba-coral hover:text-ceiba-coral rounded-md transition-all font-semibold cursor-pointer"
                  >
                    Cerrar Sesión
                  </DropdownMenuItem>
                </DropdownMenuContent>
              </DropdownMenu>
            ) : (
              <Link href="/login">
                <Button
                  size="icon"
                  variant="ghost"
                  className="rounded-full hover:bg-ceiba-cream border border-transparent hover:border-ceiba-line text-ceiba-ink transition-all"
                >
                  <User className="w-5 h-5" />
                </Button>
              </Link>
            )}

            {/* Carrito */}
            <Button
              size="icon"
              variant="ghost"
              className="relative rounded-full hover:bg-ceiba-cream border border-transparent hover:border-ceiba-line text-ceiba-ink transition-all cursor-pointer"
              onClick={() => setCartOpen(true)}
            >
              <ShoppingCart className="w-5 h-5" />
              {cartItemsCount > 0 && (
                <span className="absolute -top-1.5 -right-1.5 flex h-5 w-5 items-center justify-center rounded-full bg-ceiba-coral text-[10px] font-bold text-white shadow-sm animate-pulse">
                  {cartItemsCount}
                </span>
              )}
            </Button>

            {/* Socials */}
            <div className="flex items-center gap-3 border-l border-ceiba-line pl-5 text-ceiba-ink/75">
              <a
                href="https://www.facebook.com/share/15fkBAVpr5/?mibextid=wwXIfr"
                target="_blank"
                rel="noopener noreferrer"
                className="hover:text-blue-600 transition-colors"
              >
                <Facebook className="w-4 h-4" />
              </a>
              <a
                href="https://wa.me/525578951973"
                target="_blank"
                rel="noopener noreferrer"
                className="hover:text-green-600 transition-colors"
              >
                <PhoneCall className="w-4 h-4" />
              </a>
              <a
                href="https://www.instagram.com/elhombre.globo?igsh=MXN0aDRrdndsOGRi&utm_source=qr"
                target="_blank"
                rel="noopener noreferrer"
                className="hover:text-pink-600 transition-colors"
              >
                <Instagram className="w-4 h-4" />
              </a>
            </div>
          </div>

          {/* Botón hamburguesa móvil */}
          <div className="flex items-center gap-4 lg:hidden">
            <Button
              size="icon"
              variant="ghost"
              className="relative rounded-full hover:bg-ceiba-cream border border-ceiba-line text-ceiba-ink"
              onClick={() => setCartOpen(true)}
            >
              <ShoppingCart className="w-4 h-4" />
              {cartItemsCount > 0 && (
                <span className="absolute -top-1 -right-1 flex h-4 w-4 items-center justify-center rounded-full bg-ceiba-coral text-[8px] font-bold text-white">
                  {cartItemsCount}
                </span>
              )}
            </Button>

            <Button
              size="icon"
              variant="ghost"
              className="rounded-full hover:bg-ceiba-cream border border-ceiba-line text-ceiba-ink"
              onClick={() => setMobileMenuOpen(!mobileMenuOpen)}
            >
              {mobileMenuOpen ? <X className="w-4 h-4" /> : <Menu className="w-4 h-4" />}
            </Button>
          </div>
        </div>

        {/* Menú móvil Offcanvas */}
        {mobileMenuOpen && (
          <div className="lg:hidden absolute top-18 left-0 w-full bg-ceiba-cream border-b border-ceiba-line shadow-lg p-5 space-y-4 animate-in slide-in-from-top duration-250">
            <div className="flex flex-col gap-3 font-semibold text-sm tracking-wider text-ceiba-ink">
              {navLinks.map((link) => (
                <Link
                  key={link.path}
                  href={link.path}
                  onClick={() => setMobileMenuOpen(false)}
                  className="px-3 py-2 rounded-lg hover:bg-ceiba-line transition-all"
                >
                  {link.name}
                </Link>
              ))}

              <div className="px-3 py-2 text-xs font-bold text-ceiba-ink/40 tracking-widest mt-2 uppercase">
                Menú de Productos
              </div>
              {menuItems.map((item) => (
                <Link
                  key={item.path}
                  href={item.path}
                  onClick={() => setMobileMenuOpen(false)}
                  className="px-6 py-2 rounded-lg hover:bg-ceiba-line transition-all"
                >
                  {item.name}
                </Link>
              ))}
            </div>

            <div className="pt-4 border-t border-ceiba-line flex items-center justify-between">
              {authenticated ? (
                <div className="flex items-center gap-3">
                  <div className="w-8 h-8 rounded-full bg-ceiba-ink text-ceiba-paper flex items-center justify-center text-xs font-bold">
                    {user?.name?.[0] ?? 'U'}
                  </div>
                  <div className="text-xs">
                    <p className="font-semibold text-ceiba-ink">{user?.name}</p>
                    <button
                      onClick={() => {
                        setMobileMenuOpen(false);
                        logout();
                      }}
                      className="text-ceiba-coral font-bold mt-0.5 hover:underline"
                    >
                      Cerrar Sesión
                    </button>
                  </div>
                </div>
              ) : (
                <Link
                  href="/login"
                  onClick={() => setMobileMenuOpen(false)}
                  className="flex items-center gap-2 text-sm font-bold text-ceiba-ink hover:text-ceiba-leaf"
                >
                  <User className="w-4 h-4" />
                  Iniciar Sesión
                </Link>
              )}

              <div className="flex items-center gap-3 text-ceiba-ink/75">
                <a
                  href="https://www.facebook.com/share/15fkBAVpr5/?mibextid=wwXIfr"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="hover:text-blue-600 transition-colors"
                >
                  <Facebook className="w-4 h-4" />
                </a>
                <a
                  href="https://wa.me/525578951973"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="hover:text-green-600 transition-colors"
                >
                  <PhoneCall className="w-4 h-4" />
                </a>
                <a
                  href="https://www.instagram.com/elhombre.globo?igsh=MXN0aDRrdndsOGRi&utm_source=qr"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="hover:text-pink-600 transition-colors"
                >
                  <Instagram className="w-4 h-4" />
                </a>
              </div>
            </div>
          </div>
        )}
      </header>

      <CartDrawer open={cartOpen} onOpenChange={setCartOpen} />
    </>
  );
}

// deliveryFront/delivery-frontendd/src/app/utils/navbar-home/navbar-home.component.ts
import { ChangeDetectorRef, Component, computed } from '@angular/core';
import {  AvatarModule } from 'primeng/avatar';
import { BadgeModule } from 'primeng/badge';
import { ButtonModule } from 'primeng/button';
import { OverlayBadgeModule } from 'primeng/overlaybadge';
import { DrawerModule } from 'primeng/drawer';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { CartService } from '../../services/cart.service';
import { CartItem } from '../../model/Dtos';
import { DataViewModule } from 'primeng/dataview';
import { PaginatorModule } from 'primeng/paginator';
import { environment } from '../../../environments/environment';


@Component({
  selector: 'app-navbar-home',
  imports: [ AvatarModule, BadgeModule,OverlayBadgeModule,ButtonModule,DrawerModule,CommonModule,RouterModule,DataViewModule
    ,PaginatorModule
  ],
  templateUrl: './navbar-home.component.html',
  styleUrl: './navbar-home.component.scss'
})
export class NavbarHomeComponent {
  visible: boolean = false;

  constructor(public cartService: CartService ,private cdr: ChangeDetectorRef){}

  
  // Crea un signal computado que siempre emite una nueva referencia
  cartItems = computed(() => this.cartService.getCartItems());
  



// Controlar la visibilidad del drawer
  cartDrawerVisible: boolean = false;

   // Métodos del carrito (ahora usan directamente el servicio)
  removeFromCart(productId: number): void {
    this.cartService.removeFromCart(productId);
    this.cdr.markForCheck();
  }

  increaseQuantity(productId: number): void {
    const item = this.cartService.getCartItems().find(cartItem => cartItem.product.id === productId);
    if (item) {
      this.cartService.updateQuantity(productId, item.quantity + 1);
      this.cdr.markForCheck();
    }
  }

  decreaseQuantity(productId: number): void {
    const item = this.cartService.getCartItems().find(cartItem => cartItem.product.id === productId);
    if (item && item.quantity > 1) {
      this.cartService.updateQuantity(productId, item.quantity - 1);
      this.cdr.markForCheck();
    } else {
      this.removeFromCart(productId);
    }
  }

  clearCart(): void {
    this.cartService.clearCart();
    this.cdr.markForCheck();
  }

  checkout(): void {
    console.log('Proceder al checkout:', this.cartService.getCartItems());
    this.cartDrawerVisible = false;
  }

  getImageUrl(imagePath: string | null): string {
    if (!imagePath) {
      return 'https://primefaces.org/cdn/primeng/images/galleria/galleria10.jpg';
    }
    
    if (imagePath.startsWith('http')) {
      return imagePath;
    }
    const normalizedPath = imagePath.startsWith('/') ? imagePath : `/${imagePath}`;
    return `${environment.imageBasePathProducts}${normalizedPath}`;
  }
}
<header class="sticky top-0 z-40 w-full bg-ceiba-paper border-b border-ceiba-line shadow-xs">
  <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-18 flex items-center justify-between">
    
    <div class="flex items-center gap-4">
      <!-- Hamburguesa en móvil -->
      <button (click)="visible = true"
        class="lg:hidden p-2 rounded-full hover:bg-ceiba-cream border border-ceiba-line text-ceiba-ink cursor-pointer flex items-center justify-center">
        <i class="pi pi-bars text-lg"></i>
      </button>

      <a routerLink="/" class="flex items-center gap-3 no-underline">
        <div class="w-10 h-10 rounded-full overflow-hidden border border-ceiba-line shadow-xs">
          <img src="assets/images/logoarbol.jpg" alt="Ceiba Bar Logo" class="w-full h-full object-cover" />
        </div>
        <span class="font-bold text-base tracking-wider text-ceiba-ink hidden sm:block">
          Ceiba Bar
        </span>
      </a>
    </div>

    <!-- Desktop Menu horizontal navigation -->
    <nav class="hidden lg:flex items-center gap-8 font-semibold text-sm tracking-wider text-ceiba-ink">
      <a routerLink="/" class="transition-colors hover:text-ceiba-leaf no-underline">INICIO</a>
      
      <!-- Menú Dropdown -->
      <div class="relative group">
        <a class="flex items-center gap-1 transition-colors hover:text-ceiba-leaf no-underline cursor-pointer py-2">
          MENÚ <i class="pi pi-chevron-down text-[10px]"></i>
        </a>
        <div class="absolute top-full left-0 w-40 opacity-0 pointer-events-none group-hover:opacity-100 group-hover:pointer-events-auto transition-all duration-200 z-50 pt-2">
          <div class="bg-white border border-ceiba-line rounded-xl shadow-lg py-1">
            <a routerLink="/menu/drinks" class="block px-4 py-2 text-xs font-bold text-ceiba-ink hover:bg-ceiba-cream/50 hover:text-ceiba-leaf no-underline">Drinks</a>
            <a routerLink="/menu/snack" class="block px-4 py-2 text-xs font-bold text-ceiba-ink hover:bg-ceiba-cream/50 hover:text-ceiba-leaf no-underline">Snacks</a>
            <a routerLink="/menu/recetario" class="block px-4 py-2 text-xs font-bold text-ceiba-ink hover:bg-ceiba-cream/50 hover:text-ceiba-leaf no-underline">Recetario</a>
          </div>
        </div>
      </div>
    </nav>

    <!-- Right Actions -->
    <div class="flex items-center gap-3">
      <!-- Perfil/Login -->
      <button [routerLink]="['/login']"
        class="p-2.5 rounded-full hover:bg-ceiba-cream border border-ceiba-line text-ceiba-ink cursor-pointer flex items-center justify-center"
        title="Iniciar Sesión / Mi Perfil">
        <i class="pi pi-user text-lg"></i>
      </button>

      <!-- Carrito -->
      <button (click)="cartDrawerVisible = true"
        class="relative p-2.5 rounded-full hover:bg-ceiba-cream border border-ceiba-line text-ceiba-ink cursor-pointer flex items-center justify-center">
        <i class="pi pi-shopping-cart text-lg"></i>
        <span *ngIf="cartService.cartItemsCount() > 0"
          class="absolute -top-1 -right-1 flex h-4.5 w-4.5 items-center justify-center rounded-full bg-ceiba-coral text-[9px] font-extrabold text-white">
          {{ cartService.cartItemsCount() }}
        </span>
      </button>

      <!-- Redes Sociales (Desktop Only) -->
      <div class="hidden sm:flex items-center gap-1 border-l border-ceiba-line pl-3">
        <a href="https://www.facebook.com/share/15fkBAVpr5/?mibextid=wwXIfr" target="_blank" rel="noopener noreferrer"
          class="p-2 hover:text-ceiba-leaf text-ceiba-ink/70 flex items-center justify-center">
          <i class="pi pi-facebook text-base"></i>
        </a>
        <a href="https://wa.me/525578951973" target="_blank" rel="noopener noreferrer"
          class="p-2 hover:text-ceiba-leaf text-ceiba-ink/70 flex items-center justify-center">
          <i class="pi pi-whatsapp text-base"></i>
        </a>
        <a href="https://www.instagram.com/elhombre.globo?igsh=MXN0aDRrdndsOGRi&utm_source=qr" target="_blank" rel="noopener noreferrer"
          class="p-2 hover:text-ceiba-leaf text-ceiba-ink/70 flex items-center justify-center">
          <i class="pi pi-instagram text-base"></i>
        </a>
      </div>
    </div>

  </div>
</header>

<!-- Left Drawer for Mobile Navigation -->
<p-drawer [(visible)]="visible" position="left" [blockScroll]="true" [dismissible]="true"
  [showCloseIcon]="true" [style]="{'width': '300px'}" styleClass="ceiba-sidebar-left">
  <ng-template pTemplate="header">
    <div class="flex items-center gap-3 py-2">
      <div class="w-12 h-12 rounded-full overflow-hidden border border-ceiba-line shadow-xs">
        <img src="assets/images/logoarbol.jpg" alt="Ceiba Bar Logo" class="w-full h-full object-cover" />
      </div>
      <span class="font-bold text-sm text-ceiba-ink">Ceiba Bar</span>
    </div>
  </ng-template>

  <div class="flex flex-col h-full py-4 justify-between">
    <div class="space-y-2">
      <a routerLink="/" (click)="visible = false"
        class="flex items-center gap-3 px-4 py-3 rounded-xl text-sm font-semibold tracking-wide hover:bg-ceiba-line/10 text-ceiba-ink no-underline transition-all">
        <i class="pi pi-home text-ceiba-ink/75"></i>
        Inicio
      </a>
      
      <!-- Sección Menú Acordeón en móvil -->
      <div class="px-4 py-2 text-xs font-bold text-ceiba-ink/40 uppercase tracking-wider">Menú</div>
      <a routerLink="/menu/drinks" (click)="visible = false"
        class="flex items-center gap-3 px-6 py-2 rounded-xl text-sm font-semibold tracking-wide hover:bg-ceiba-line/10 text-ceiba-ink no-underline transition-all">
        <i class="pi pi-minus text-[10px] text-ceiba-leaf"></i>
        Drinks
      </a>
      <a routerLink="/menu/snack" (click)="visible = false"
        class="flex items-center gap-3 px-6 py-2 rounded-xl text-sm font-semibold tracking-wide hover:bg-ceiba-line/10 text-ceiba-ink no-underline transition-all">
        <i class="pi pi-minus text-[10px] text-ceiba-leaf"></i>
        Snacks
      </a>
      <a routerLink="/menu/recetario" (click)="visible = false"
        class="flex items-center gap-3 px-6 py-2 rounded-xl text-sm font-semibold tracking-wide hover:bg-ceiba-line/10 text-ceiba-ink no-underline transition-all">
        <i class="pi pi-minus text-[10px] text-ceiba-leaf"></i>
        Recetario
      </a>

      <!-- Perfil/Iniciar Sesión -->
      <div class="px-4 py-2 border-t border-ceiba-line/50 mt-4 pt-4">
        <a [routerLink]="['/login']" (click)="visible = false"
          class="flex items-center gap-3 px-4 py-3 bg-ceiba-cream rounded-xl text-sm font-semibold tracking-wide hover:bg-ceiba-line/15 text-ceiba-ink no-underline transition-all">
          <i class="pi pi-user text-ceiba-ink/75"></i>
          Iniciar Sesión
        </a>
      </div>
    </div>

    <!-- Redes Sociales en móvil footer -->
    <div class="pt-4 border-t border-ceiba-line mt-auto flex justify-center gap-4 py-2">
      <a href="https://www.facebook.com/share/15fkBAVpr5/?mibextid=wwXIfr" target="_blank" rel="noopener noreferrer"
        class="p-2.5 rounded-full hover:bg-ceiba-line/10 text-ceiba-ink/80 flex items-center justify-center border border-ceiba-line">
        <i class="pi pi-facebook text-sm"></i>
      </a>
      <a href="https://wa.me/525578951973" target="_blank" rel="noopener noreferrer"
        class="p-2.5 rounded-full hover:bg-ceiba-line/10 text-ceiba-ink/80 flex items-center justify-center border border-ceiba-line">
        <i class="pi pi-whatsapp text-sm"></i>
      </a>
      <a href="https://www.instagram.com/elhombre.globo?igsh=MXN0aDRrdndsOGRi&utm_source=qr" target="_blank" rel="noopener noreferrer"
        class="p-2.5 rounded-full hover:bg-ceiba-line/10 text-ceiba-ink/80 flex items-center justify-center border border-ceiba-line">
        <i class="pi pi-instagram text-sm"></i>
      </a>
    </div>
  </div>
</p-drawer>

<!-- Right Drawer for Cart -->
<p-drawer [(visible)]="cartDrawerVisible" position="right" [blockScroll]="true" [dismissible]="true"
  [showCloseIcon]="true" [style]="{'width': '450px'}" styleClass="ceiba-cart-drawer">
  
  <ng-template pTemplate="header">
    <div class="flex items-center justify-between w-full pr-4 py-1">
      <h3 class="font-extrabold text-lg text-ceiba-ink m-0">Tu Carrito 🛒</h3>
      <span class="bg-ceiba-cream px-3 py-1.5 rounded-full border border-ceiba-line text-xs font-bold text-ceiba-ink">
        {{ cartService.cartItemsCount() }} items
      </span>
    </div>
  </ng-template>

  <div class="flex flex-col h-full justify-between">
    <!-- Items list -->
    <div class="flex-1 overflow-y-auto py-4 space-y-4">
      @if(cartService.getCartItems().length === 0){
        <div class="flex flex-col items-center justify-center py-16 text-center">
          <i class="pi pi-shopping-cart text-5xl text-ceiba-ink/20 mb-3"></i>
          <p class="font-bold text-sm text-ceiba-ink">Tu carrito está vacío</p>
          <button pButton label="Seguir Comprando" class="mt-4 bg-ceiba-ink text-white border-none rounded-xl py-2 px-4 text-xs font-bold"
            (click)="cartDrawerVisible = false"></button>
        </div>
      } @else {
        <div *ngFor="let item of cartService.getCartItems()"
          class="flex items-center gap-4 bg-white border border-ceiba-line p-3 rounded-2xl shadow-xs hover:shadow-md transition-all">
          <div class="w-16 h-16 rounded-xl overflow-hidden border border-ceiba-line flex-shrink-0">
            <img [src]="getImageUrl(item.product.image)" [alt]="item.product.name" class="w-full h-full object-cover" />
          </div>
          
          <div class="flex-1 text-left min-w-0">
            <h4 class="font-extrabold text-sm text-ceiba-ink truncate m-0">{{ item.product.name }}</h4>
            <p class="text-xs text-ceiba-leaf-dark font-extrabold mt-1 m-0">{{ item.product.price | currency:'MXN':'symbol':'1.2-2' }}</p>
          </div>
          
          <div class="flex flex-col items-end gap-2">
            <div class="flex items-center bg-ceiba-cream border border-ceiba-line rounded-full p-1 gap-2 scale-90">
              <button (click)="decreaseQuantity(item.product.id)"
                class="w-6 h-6 rounded-full bg-white border border-ceiba-line text-ceiba-ink font-bold hover:bg-ceiba-cream transition-all flex items-center justify-center">-</button>
              <span class="font-extrabold text-xs text-ceiba-ink min-w-[15px] text-center">{{ item.quantity }}</span>
              <button (click)="increaseQuantity(item.product.id)"
                class="w-6 h-6 rounded-full bg-white border border-ceiba-line text-ceiba-ink font-bold hover:bg-ceiba-cream transition-all flex items-center justify-center">+</button>
            </div>
            
            <button (click)="removeFromCart(item.product.id)"
              class="p-2 rounded-full bg-ceiba-coral/10 hover:bg-ceiba-coral/20 text-ceiba-coral border-none cursor-pointer flex items-center justify-center scale-90">
              <i class="pi pi-trash text-xs"></i>
            </button>
          </div>
        </div>
      }
    </div>

    <!-- Footer total and actions -->
    <div *ngIf="cartService.getCartItems().length > 0" class="pt-6 border-t border-ceiba-line space-y-4">
      <div class="flex items-center justify-between px-2">
        <span class="text-sm font-semibold text-ceiba-ink/70">Subtotal</span>
        <span class="font-black text-xl text-ceiba-ink">{{ cartService.cartTotal() | currency:'MXN':'symbol':'1.2-2' }}</span>
      </div>
      
      <div class="grid grid-cols-2 gap-3 pb-6">
        <button pButton label="Limpiar" icon="pi pi-trash"
          class="border-ceiba-line text-ceiba-ink hover:bg-ceiba-cream rounded-xl py-3 font-bold transition-all p-button-outlined"
          (click)="clearCart()"></button>
        <button pButton label="Pagar" icon="pi pi-credit-card"
          class="bg-ceiba-leaf hover:bg-ceiba-leaf-dark text-white border-none rounded-xl py-3 font-bold transition-all"
          (click)="cartService.finalizarCompra(); cartDrawerVisible = false"></button>
      </div>
    </div>
  </div>

</p-drawer>
